"""Shared CLI command and runtime artifact names."""

from __future__ import annotations

BRONZE_BUILDER_COMMAND = "l2-bronze-builder"
LEGACY_BRONZE_BUILDER_COMMAND = "bronze-builder"
OPTIONS_BRONZE_BUILDER_COMMAND = "options-bronze-builder"
INSTRUMENT_METADATA_BRONZE_BUILDER_COMMAND = "instrument-metadata-bronze-builder"
INDEX_PRICE_BRONZE_BUILDER_COMMAND = "index-price-bronze-builder"
INDEX_PRICE_SILVER_BUILDER_COMMAND = "index-price-silver-builder"
INDEX_PRICE_GOLD_BUILDER_COMMAND = "index-price-gold-builder"
INSTRUMENT_METADATA_SILVER_BUILDER_COMMAND = "instrument-metadata-silver-builder"
INSTRUMENT_METADATA_GOLD_BUILDER_COMMAND = "instrument-metadata-gold-builder"
OPTIONS_SILVER_BUILDER_COMMAND = "options-silver-builder"
OPTIONS_GOLD_BUILDER_COMMAND = "options-gold-builder"
SILVER_BUILDER_COMMAND = "l2-silver-builder"
LEGACY_SILVER_BUILDER_COMMAND = "silver-builder"
GOLD_BUILDER_COMMAND = "l2-gold-builder"
LEGACY_GOLD_BUILDER_COMMAND = "gold-builder"
VALIDATE_SYMBOLS_COMMAND = "validate-symbols"
